import { NextRequest, NextResponse } from 'next/server';

// Allowed origins for CORS
const ALLOWED_ORIGINS = (process.env.ALLOWED_ORIGINS || 'http://localhost:3000')
  .split(',')
  .map(o => o.trim());

function getCorsHeaders(request: NextRequest): Record<string, string> {
  const origin = request.headers.get('origin') || '';
  if (ALLOWED_ORIGINS.includes(origin)) {
    return {
      'Access-Control-Allow-Origin': origin,
      'Access-Control-Allow-Methods': 'POST, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type, Authorization',
      'Access-Control-Max-Age': '86400',
      'Vary': 'Origin',
    };
  }
  return {};
}

// Send email via SendGrid API directly
async function sendEmailLocally(email: string, posts: string[]): Promise<boolean> {
  const sendgridKey = process.env.SENDGRID_API_KEY;
  const fromEmail = process.env.FROM_EMAIL || 'noreply@localhost';

  if (!sendgridKey || sendgridKey === 'SG.your_sendgrid_api_key_here') {
    console.warn('SENDGRID_API_KEY not configured — email not sent');
    return false;
  }

  const htmlContent = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
      <h2 style="color: #1a1a2e;">Your Social Media Posts</h2>
      <p>Here are your generated social media posts:</p>
      ${posts.map((post, i) => `
        <div style="background: #f8f9fa; border-left: 4px solid #4f46e5; padding: 12px; margin: 12px 0; border-radius: 4px;">
          <p style="margin: 0; white-space: pre-wrap;">${escapeHtml(post)}</p>
        </div>
      `).join('')}
      <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 24px 0;" />
      <p style="color: #6b7280; font-size: 12px;">
        Generated by Content Repurposing Engine
      </p>
    </div>
  `;

  try {
    const response = await fetch('https://api.sendgrid.com/v3/mail/send', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${sendgridKey}`,
      },
      body: JSON.stringify({
        personalizations: [{ to: [{ email }] }],
        from: { email: fromEmail },
        subject: 'Your Generated Social Media Posts',
        content: [{ type: 'text/html', value: htmlContent }],
      }),
      signal: AbortSignal.timeout(15000),
    });

    return response.ok;
  } catch (err) {
    console.error('SendGrid request failed:', err);
    return false;
  }
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&')
    .replace(/</g, '<')
    .replace(/>/g, '>')
    .replace(/"/g, '"')
    .replace(/'/g, '&#039;');
}

export async function POST(request: NextRequest) {
  try {
    const { email, posts } = await request.json();

    // Validate inputs
    if (!email || !posts) {
      return NextResponse.json(
        { error: 'Email and posts are required' },
        { status: 400, headers: getCorsHeaders(request) }
      );
    }

    // Basic email validation
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
      return NextResponse.json(
        { error: 'Invalid email address' },
        { status: 400, headers: getCorsHeaders(request) }
      );
    }

    if (!Array.isArray(posts) || posts.length === 0) {
      return NextResponse.json(
        { error: 'Posts must be a non-empty array' },
        { status: 400, headers: getCorsHeaders(request) }
      );
    }

    // Check if Appwrite is configured and enabled
    const useAppwrite = process.env.USE_APPWRITE_EMAIL === 'true';
    const appwriteProjectId = process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID;
    const appwriteEndpoint = process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT;

    if (useAppwrite && appwriteProjectId && appwriteProjectId !== 'your-project-id-here') {
      try {
        const response = await fetch(
          `${appwriteEndpoint}/v1/functions/send-email/execute`,
          {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
              'X-Appwrite-Project': appwriteProjectId,
            },
            body: JSON.stringify({ email, posts }),
            signal: AbortSignal.timeout(15000),
          }
        );

        if (response.ok) {
          const result = await response.json();
          return NextResponse.json(result, { headers: getCorsHeaders(request) });
        }

        console.warn('Appwrite email function failed, falling back to local');
      } catch (err) {
        console.warn('Appwrite email request failed, falling back to local:', err);
      }
    }

    // Default: send email locally via SendGrid
    const sent = await sendEmailLocally(email, posts);

    return NextResponse.json(
      {
        success: sent,
        message: sent
          ? 'Email sent successfully'
          : 'Email service not configured — set SENDGRID_API_KEY to enable email delivery',
      },
      { headers: getCorsHeaders(request) }
    );
  } catch (error: any) {
    console.error('Error sending email:', error);
    return NextResponse.json(
      { error: 'Failed to send email' },
      { status: 500, headers: getCorsHeaders(request) }
    );
  }
}

// Handle CORS preflight
export async function OPTIONS(request: NextRequest) {
  return new NextResponse(null, {
    status: 204,
    headers: {
      ...getCorsHeaders(request),
      'Access-Control-Max-Age': '86400',
    },
  });
}
